---
swagger: "2.0"
info:
  description: "gestion des produits"
  version: "0.9.0"
  title: "User API"
host: "localhost:3000"
schemes:
- "http"
produces:
- "application/json"
paths:
  /user:
    get:
      summary: "authentifier un user"
      description: "bla"
      operationId: "userGET"
      parameters:
      - name: "login"
        in: "query"
        description: "id du produit."
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "mot de passe"
        required: true
        type: "string"
      responses:
        200:
          description: "chaine"
          schema:
            type: "boolean"
        default:
          description: "toujours faux"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Default"
definitions:
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
